import Image from 'next/image'
import './globals.scss'
import { Inter } from 'next/font/google'

import Logo from '../image/Logo.png';
import AuthBtn from './component/AuthBtn';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className='navBar'>
          <Image className='Logo' src={Logo} alt='Logo' />
          <ul>
            <li>메뉴1</li>
            <li>메뉴1</li>
            <li>메뉴1</li>
            <li>메뉴1</li>
          </ul>
          <AuthBtn/>
        </div>
        {children}
      </body>
    </html>
  )
}
